### ISSUE TITLE
[Question] Does this suit CentOS 6.10 Running Asterisk?

### ISSUE THREAD

**Issue by HorselessName** [oussamahammami/Linux-Tuning-SIP-Servers#1]
Hello.
My Asterisk is at High CPU usage and i wonder if your Sysctl.conf works well on CentOS 6.10.
Is it ok for me to test it?

**Comment by oussamahammami** [comment]
Transcoding from or to a frequency domain type codec is the most CPU intensive activity normally associated with an Asterisk system.

Check your translation path.
